#!/usr/bin/env bash

if [ "$1" == "enter-root" ]; then
    docker-compose exec php /bin/zsh
elif [ "$1" == "enter" ]; then
    docker-compose exec -u utente php /bin/zsh
elif [ $# -gt 0 ]; then
    docker-compose "$@"
else
    docker-compose ps
fi
