version: '3.7'

volumes:
  app_database: {}

services:
  php:
    image: matiux/php:7.2.11-fpm-alpine3.8-dev
    hostname: host
    volumes:
      - ./:/var/www/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - servicedb
    environment:
      - PMA_HOST=servicedb

  servicedb:
    image: mysql:5.7
    volumes:
      - app_database:/var/lib/mysql
    command: mysqld --sql_mode=""
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=idy
