#!/usr/bin/env php
<?php

require __DIR__.'/../../vendor/autoload.php';

use HexagonalArchitecture\Step04\Idea\Application\Service\CreaIdea;
use HexagonalArchitecture\Step04\Idea\Infrastructure\Communication\Console\CreateIdeaCommand;
use HexagonalArchitecture\Step04\Idea\Infrastructure\Domain\Model\MySql\MySqlIdee;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(
    new CreateIdeaCommand(
        new CreaIdea(new MySqlIdee())
    )
);

$application->run();
